# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5012deeba942416d907db7af3d66f9a9d5ef11bb89e728e97051809b80531509d5b263aba3a8e68e6b0c206d40d58c3532bf0cc865c7b26f6f4a2410b13c57cb

test:
  secret_key_base: 315ebd8558a2f2787a50edcb70dca1b31136e5d390922d0102d370fb222edb45b11ddd36a22c086610cfc6d30bd09e57121aa79a2100e487da2a5c00d8a91248

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
